name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ develop ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v4.2.2

    # Uses .NET SDK
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish SHDDB.Standalone/SHDDB.Standalone.csproj -c Release -o release --nologo

    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        folder: release/wwwroot
          
